runtime: python311
instance_class: F1
service: predictor

# workers = 1 for F1, workers = 2 for F2, workers = 4 for F4
entrypoint: gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind :$PORT app.main:application
